<?xml version="1.0"?>
<robot name="wchair" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find wheelchair_description)/urdf/w.urdf.xacro" /> 
<xacro:include filename="$(find wheelchair_description)/urdf/t.urdf.xacro" /> 
<xacro:include filename="$(find wheelchair_description)/urdf/c.urdf.xacro" /> 

<!-- ##################################################################### -->
	<!-- PROPERTY LIST -->
	<property name="M_PI" value="3.1415926535897931" />
	<property name="base_x" value="0.75" />
	<property name="base_y" value="0.5" />
	<property name="base_z" value="0.30" />
	<property name="base_mass" value="5.0"/>
	
	<property name="hokuyo_size" value="0.05"/>
	<property name="imu_size" value="0.05"/>
  	<property name="camera_size" value="0.05" />

	
	<property name="rate_sensor" value="50.0"/>
	<property name="d_grey" value="0.15"/>
	
<!-- ##################################################################### -->	
	<!-- Base Link -->
	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${base_x} ${base_y} ${base_z}"/></geometry>
			<material name="blue"><color rgba="0 0 0.6 1"/></material>
		</visual>
		<!-- Base collision -->
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${base_x} ${base_y} ${base_z}"/></geometry>
		</collision>
		<inertial>
			<mass value="${base_mass}"/>
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyx="0.0" iyy="0.21" iyz="0.0" izx="0.0" izy="0.0" izz="0.13"/>
		</inertial>
	</link>
	<gazebo reference="base_link">
		<material>Gazebo/SkyBlue</material>
		<!--<turnGravityOff>false</turnGravityOff>-->
	</gazebo>
<!-- ##################################################################### -->
<!-- Per far funzionare il MOVE_BASE abbiamo invertito le ruote destra e sinistra, a quanto pare l'asse Y e orientato in modo opposto rispetto a come pensavamo -->
	<!-- Top -->
	<top lr="left" parent="base_link" translateX="0.375" translateY="-0.275" translateZ="0" />
	<top lr="right" parent="base_link" translateX="0.375" translateY="0.275" translateZ="0" />
<!-- ##################################################################### -->
	<!-- Caster -->
	<caster lr="left" parent="base_link" translateX="0.375" translateY="-0.275" translateZ="-0.15" />
	<caster lr="right" parent="base_link" translateX="0.375" translateY="0.275" translateZ="-0.15" />
<!-- ##################################################################### -->
	<!-- Wheels-->
	<wheel lr="left" parent="base_link" translateX="-0.15" translateY="-0.3" translateZ="-0.05" flipY="1" />
	<wheel lr="right" parent="base_link" translateX="-0.15" translateY="0.3" translateZ="-0.05" flipY="1" />
<!-- ##################################################################### -->
	<!-- PEDANE -->
	<link name="pedana1">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.02 0.5 0.35" /></geometry>
			<material name="dark_grey"><color rgba="${d_grey} ${d_grey} ${d_grey} 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.02 0.5 0.35" /></geometry>
		</collision>
	</link>
	<joint name="joint_pedana1" type="fixed">
		<parent link="base_link"/>
		<child link="pedana1"/>
		<origin xyz="0.42 0 0.05" rpy="0 -0.40 0" />
	</joint>
	<gazebo reference="pedana1">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ##################################################################### -->
	<!-- PEDANA 2 -->
	<link name="pedana2">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.25 0.5 0.02" /></geometry>
			<material name="dark_grey"><color rgba="${d_grey} ${d_grey} ${d_grey} 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.25 0.5 0.02"  /></geometry>
		</collision>
	</link>
	<joint name="joint_pedana2" type="fixed">
		<parent link="base_link"/>
		<child link="pedana2"/>
		<origin xyz="0.60 0 -0.12" rpy="0 0 0" />
	</joint>
	<gazebo reference="pedana2">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ##################################################################### -->
	<!-- SEDILE -->
	<link name="sedile">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.35 0.5 0.08" /></geometry>
			<material name="dark_grey"><color rgba="${d_grey} ${d_grey} ${d_grey} 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.35 0.5 0.08" /></geometry>
		</collision>
	</link>
	<joint name="joint_sedile" type="fixed">
		<parent link="base_link"/>
		<child link="sedile"/>
		<origin xyz="0.19 0 0.19" rpy="0 0 0" />
	</joint>
	<gazebo reference="sedile">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ##################################################################### -->
	<!-- SCHIENALE -->
	<link name="schienale">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.06 0.5 0.48" /></geometry>
			<material name="dark_grey"><color rgba="${d_grey} ${d_grey} ${d_grey} 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.06 0.5 0.48" /></geometry>
		</collision>
	</link>
	<joint name="joint_schienale" type="fixed">
		<parent link="base_link"/>
		<child link="schienale"/>
		<origin xyz="0 0 0.45" rpy="0 -0.2 0" />
	</joint>
	<gazebo reference="schienale">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ##################################################################### -->
	<!-- BRACCIOLO DX-->
	<link name="bracciolo_dx">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.40 0.06 0.04" /></geometry>
			<material name="dark_grey"><color rgba="${d_grey} ${d_grey} ${d_grey} 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.40 0.06 0.04" /></geometry>
		</collision>
	</link>
	<joint name="joint_bracciolo_dx" type="fixed">
		<parent link="base_link"/>
		<child link="bracciolo_dx"/>
		<origin xyz="0.16 -0.28 0.4" rpy="0 0 0" />
	</joint>
	<gazebo reference="bracciolo_dx">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ##################################################################### -->
	<!-- BRACCIOLO SX-->
	<link name="bracciolo_sx">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.40 0.06 0.04" /></geometry>
			<material name="dark_grey"><color rgba="${d_grey} ${d_grey} ${d_grey} 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.40 0.06 0.04" /></geometry>
		</collision>
	</link>
	<joint name="joint_bracciolo_sx" type="fixed">
		<parent link="base_link"/>
		<child link="bracciolo_sx"/>
		<origin xyz="0.16 0.28 0.4" rpy="0 0 0" />
	</joint>
	<gazebo reference="bracciolo_sx">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ##################################################################### -->
	<!-- SENSOR hokuyo -->
	<link name="hokuyo_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/></geometry>
			<material name="black"><color rgba="0 0 0 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/></geometry>
		</collision>
	</link> 
	<joint name="hokuyo_joint" type="fixed">
		<origin xyz="0.7 0 -0.085" rpy="0 0 0" />
		<parent link="base_link"/>
		<child link="hokuyo_link" />
	</joint>
	<gazebo reference="hokuyo_link">
		<material>Gazebo/Black</material>
		<!-- <turnGravityOff>false</turnGravityOff> -->
		<sensor type="ray" name="head_hokuyo_sensor">
			<pose>${hokuyo_size/2} 0 0 0 0 0</pose>
			<visualize>false</visualize>
			<update_rate>${rate_sensor}</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>682</samples><!-- 240 gradi formati da step di circa 0.3515625 -->
						<resolution>1</resolution>
						<min_angle>-2.0944</min_angle> <!-- -120 gradi-->
						<max_angle>2.0944</max_angle> <!-- +120 gradi-->
					</horizontal>
				</scan>
				<range>
					<min>0.1</min>
					<max>4.0</max>
					<resolution>0.001</resolution>
				</range>
			</ray>
			<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
				<topicName>/scan</topicName>
				<frameName>hokuyo_link</frameName>
			</plugin>
		</sensor>
	</gazebo>
<!-- ##################################################################### -->
	<!-- SENSOR imu -->	
	<link name="imu_link">
  		<visual>
    		<origin rpy="0 0 0" xyz="0 0 0"/>
      		<geometry><box size="${imu_size} ${imu_size} ${imu_size}"/></geometry>
			<material name="orange"><color rgba="1 0.5 0 1"/></material>
  		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${imu_size} ${imu_size} ${imu_size}"/></geometry>
		</collision>
	</link>
	<joint name="imu_joint" type="fixed">
    	<origin xyz="${-base_x/2 + imu_size} 0 ${base_z/2+imu_size/2}" rpy="0 0 0"/>
    	<parent link="base_link"/>
    	<child link="imu_link"/>
  	</joint>
	<gazebo reference="imu_link">
		<material>Gazebo/Orange</material>
		<!-- <turnGravityOff>false</turnGravityOff> -->
		<sensor type="imu" name="imu_sensor">
			<imu>
				  <angular_velocity>
				    <x>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>2e-4</stddev>
				        <bias_mean>0.0000075</bias_mean>
				        <bias_stddev>0.0000008</bias_stddev>
				      </noise>
				    </x>
				    <y>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>2e-4</stddev>
				        <bias_mean>0.0000075</bias_mean>
				        <bias_stddev>0.0000008</bias_stddev>
				      </noise>
				    </y>
				    <z>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>2e-4</stddev>
				        <bias_mean>0.0000075</bias_mean>
				        <bias_stddev>0.0000008</bias_stddev>
				      </noise>
				    </z>
				  </angular_velocity>
				  <linear_acceleration>
				    <x>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>1.7e-2</stddev>
				        <bias_mean>0.1</bias_mean>
				        <bias_stddev>0.001</bias_stddev>
				      </noise>
				    </x>
				    <y>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>1.7e-2</stddev>
				        <bias_mean>0.1</bias_mean>
				        <bias_stddev>0.001</bias_stddev>
				      </noise>
				    </y>
				    <z>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>1.7e-2</stddev>
				        <bias_mean>0.1</bias_mean>
				        <bias_stddev>0.001</bias_stddev>
				      </noise>
				    </z>
				  </linear_acceleration>
			</imu>
			<pose>0 0 0 0 0 0</pose>
			<update_rate>${rate_sensor}</update_rate>
    		<plugin name="gazebo_ros_imu_controller" filename="libgazebo_ros_imu_sensor.so"> 
    	  		<topicName>/imu</topicName>
    	  		<frameName>imu_link</frameName>
    	  		<alwaysOn>true</alwaysOn>
    	  		<bodyName>base_link</bodyName>
    	  		<gaussianNoise>0.5</gaussianNoise> 
    	  		<serviceName>imu/calibrate</serviceName>
    	  		<rpyOffset>0 0 0</rpyOffset> 
				<accelDrift>0.5 0.5 0.5</accelDrift>
				<accelGaussianNoise>0.35 0.35 0.35</accelGaussianNoise>
				<rateDrift>0.1 0.1 0.1</rateDrift>
				<rateGaussianNoise>0.05 0.05 0.05</rateGaussianNoise>
    		</plugin>
    	</sensor> 
  	</gazebo>
<!-- ##################################################################### -->
   <!--SUPPORTO-->
	<link name="supporto1">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${camera_size} ${camera_size} 0.625" /></geometry>
			<material name="blue"><color rgba="0 0 0.6 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${camera_size} ${camera_size} 0.625" /></geometry>
		</collision>
	</link>
	<joint name="joint_supporto1" type="fixed">
		<parent link="base_link"/>
		<child link="supporto1"/>
		<origin xyz="-0.15 0 0.3125" rpy="0 0 0" />
	</joint>
	<gazebo reference="supporto1">
  		<material>Gazebo/SkyBlue</material>
  	</gazebo>
	
	<link name="supporto2">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.15 0.5 ${camera_size}" /></geometry>
			<material name="blue"><color rgba="0 0 0.6 1"/></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.15 0.5 ${camera_size}" /></geometry>
		</collision>
	</link>
	<joint name="joint_supporto2" type="fixed">
		<parent link="base_link"/>
		<child link="supporto2"/>
		<origin xyz="-0.15 0 ${0.6+camera_size}" rpy="0 0 0" />
	</joint>
	<gazebo reference="supporto2">
  		<material>Gazebo/SkyBlue</material>
  	</gazebo>
<!-- ##################################################################### -->
	<!-- SENSOR camera -->	
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${camera_size} ${camera_size} ${camera_size}"/></geometry>
	  <material name="red"><color rgba="1 0 0 1"/></material>
    </visual>
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<geometry><box size="${camera_size} ${camera_size} ${camera_size}"/></geometry>
	</collision>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="-0.15 0 ${0.6+camera_size*2}" rpy="0 -1.5708 0" /> <!-- pitch a -1.5708 per puntare in alto -->
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <gazebo reference="camera_link">
	<material>Gazebo/Red</material>
    <sensor type="camera" name="camera_sensor">
      <update_rate>${rate_sensor}</update_rate>
      <camera>
        <horizontal_fov>1.047197551</horizontal_fov> <!--60 gradi-->
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.002</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.0</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
		<updateRate>20.0</updateRate>
		<cameraName>wchair/camera_sensor</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.0</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
        <Cx>319.729675</Cx>
        <Cy>238.722791</Cy>
        <focalLength>554.668244</focalLength> <!--matematicamente 554.256258422-->
      </plugin>
    </sensor>
  </gazebo>

<!-- ##################################################################### -->
	<!-- Differential drive controller  -->
	<!-- Per muove il robot in Gazebo dobbiamo aggiungere questo plugin "libgazebo_ros_diff_drive.so" -->
	<gazebo>
		<plugin name="differential_drive_controller_caster" filename="libgazebo_ros_diff_drive.so">
			<legacyMode>false</legacyMode>
			<rosDebugLevel>Debug</rosDebugLevel>
			<publishWheelTF>true</publishWheelTF>
			<robotNamespace>/</robotNamespace>
			<publishTf>0</publishTf> 
			<broadcastTF>0</broadcastTF>
			<alwaysOn>true</alwaysOn>
			<publishWheelJointState>false</publishWheelJointState>
			<updateRate>${rate_sensor}</updateRate>
			<leftJoint>left_caster_joint</leftJoint>
			<rightJoint>right_caster_joint</rightJoint>
			<wheelSeparation>${base_y}</wheelSeparation>
			<wheelDiameter>0.2</wheelDiameter>
			<wheelTorque>30</wheelTorque>
			<wheelAcceleration>1.8</wheelAcceleration>
			<commandTopic>cmd_vel</commandTopic>
			<robotBaseFrame>base_link</robotBaseFrame>
			<odometryFrame>odom</odometryFrame> 
			<odometryTopic>odom</odometryTopic>
		</plugin>
		<plugin name="differential_drive_controller_wheel" filename="libgazebo_ros_diff_drive.so">
			<legacyMode>false</legacyMode>
			<rosDebugLevel>Debug</rosDebugLevel>
			<publishWheelTF>true</publishWheelTF>
			<robotNamespace>/</robotNamespace>
			<publishTf>0</publishTf> 
			<broadcastTF>0</broadcastTF>
			<alwaysOn>true</alwaysOn>
			<publishWheelJointState>true</publishWheelJointState>
			<updateRate>${rate_sensor}</updateRate>
			<leftJoint>left_wheel_joint</leftJoint>
			<rightJoint>right_wheel_joint</rightJoint>
			<wheelSeparation>${base_y}</wheelSeparation>
			<wheelDiameter>${2*wheel_radius}</wheelDiameter>
			<wheelTorque>30</wheelTorque>
			<wheelAcceleration>1.8</wheelAcceleration>
			<commandTopic>cmd_vel</commandTopic>
			<robotBaseFrame>base_link</robotBaseFrame>
			<odometryFrame>odom</odometryFrame> 
			<odometryTopic>odom</odometryTopic>
		</plugin>
		<plugin name="differential_drive_controller_top" filename="libgazebo_ros_diff_drive.so">
			<legacyMode>false</legacyMode>
			<rosDebugLevel>Debug</rosDebugLevel>
			<publishWheelTF>true</publishWheelTF>
			<robotNamespace>/</robotNamespace>
			<publishTf>0</publishTf> 
			<broadcastTF>0</broadcastTF>
			<alwaysOn>true</alwaysOn>
			<publishWheelJointState>false</publishWheelJointState>
			<updateRate>${rate_sensor}</updateRate>
			<leftJoint>left_top_joint</leftJoint>
			<rightJoint>right_top_joint</rightJoint>
			<wheelSeparation>${base_y}</wheelSeparation>
			<wheelDiameter>0.05</wheelDiameter>
			<wheelTorque>30</wheelTorque>
			<wheelAcceleration>1.8</wheelAcceleration>
			<commandTopic>cmd_vel</commandTopic>
			<robotBaseFrame>base_link</robotBaseFrame>
			<odometryFrame>odom</odometryFrame> 
			<odometryTopic>odom</odometryTopic>
		</plugin>
	</gazebo>
</robot>

