<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- MATERIALS -->
	
	
	<!-- Base Link -->
	<gazebo reference="base_link">
		<material>Gazebo/SkyBlue</material>
		<!--<turnGravityOff>false</turnGravityOff>-->
	</gazebo>
	
	<!-- Pedana 1 -->
	<gazebo reference="pedana1">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>

	<!-- Pedana 2 -->
	<gazebo reference="pedana2">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
	
	<!-- Sedile -->
	<gazebo reference="sedile">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
	
	<!-- Schienale -->
	<gazebo reference="schienale">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>

	<!-- Bracciolo DX-->
	<gazebo reference="bracciolo_dx">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>

	<!-- Bracciolo SX-->
	<gazebo reference="bracciolo_sx">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
	
	<!-- Supporti -->
	<gazebo reference="supporto1">
  		<material>Gazebo/SkyBlue</material>
  	</gazebo>
	
	<gazebo reference="supporto2">
  		<material>Gazebo/SkyBlue</material>
  	</gazebo>
	
	<!-- Ruote -->
	<gazebo reference="$left_wheel">
		<material>Gazebo/Grey</material>
	</gazebo>
	
	<gazebo reference="$right_wheel">
		<material>Gazebo/Grey</material>
	</gazebo>
	
	<!-- Caster -->
	<gazebo reference="left_caster">
		<material>Gazebo/Grey</material>
	</gazebo>
	
	<gazebo reference="right_caster">
		<material>Gazebo/Grey</material>
	</gazebo>
	
	<!-- Top -->
	<gazebo reference="left_top">
		<material>Gazebo/White</material>
	</gazebo>
	
	<gazebo reference="right_top">
		<material>Gazebo/White</material>
	</gazebo>
	
	
	
<!-- ##################################################################### -->
	
	<!-- SENSORS -->
	

	<!-- Hokuyo -->
	<gazebo reference="hokuyo_link">
		<material>Gazebo/Black</material>
		<!-- <turnGravityOff>false</turnGravityOff> -->
		<sensor type="ray" name="head_hokuyo_sensor">
			<pose>${hokuyo_size/2} 0 0 0 0 0</pose>
			<visualize>false</visualize>
			<update_rate>${rate_sensor}</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>682</samples><!-- 240 gradi formati da step di circa 0.3515625 -->
						<resolution>1</resolution>
						<min_angle>-2.0944</min_angle> <!-- -120 gradi-->
						<max_angle>2.0944</max_angle> <!-- +120 gradi-->
					</horizontal>
				</scan>
				<range>
					<min>0.1</min>
					<max>4.0</max>
					<resolution>0.001</resolution>
				</range>
			</ray>
			<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
				<topicName>/scan</topicName>
				<frameName>hokuyo_link</frameName>
			</plugin>
		</sensor>
	</gazebo>


	<!-- Imu -->	
	<gazebo reference="imu_link">
		<material>Gazebo/Orange</material>
		<!-- <turnGravityOff>false</turnGravityOff> -->
		<sensor type="imu" name="imu_sensor">
			<imu>
				  <angular_velocity>
				    <x>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>2e-4</stddev>
				        <bias_mean>0.0000075</bias_mean>
				        <bias_stddev>0.0000008</bias_stddev>
				      </noise>
				    </x>
				    <y>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>2e-4</stddev>
				        <bias_mean>0.0000075</bias_mean>
				        <bias_stddev>0.0000008</bias_stddev>
				      </noise>
				    </y>
				    <z>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>2e-4</stddev>
				        <bias_mean>0.0000075</bias_mean>
				        <bias_stddev>0.0000008</bias_stddev>
				      </noise>
				    </z>
				  </angular_velocity>
				  <linear_acceleration>
				    <x>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>1.7e-2</stddev>
				        <bias_mean>0.1</bias_mean>
				        <bias_stddev>0.001</bias_stddev>
				      </noise>
				    </x>
				    <y>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>1.7e-2</stddev>
				        <bias_mean>0.1</bias_mean>
				        <bias_stddev>0.001</bias_stddev>
				      </noise>
				    </y>
				    <z>
				      <noise type="gaussian">
				        <mean>0.0</mean>
				        <stddev>1.7e-2</stddev>
				        <bias_mean>0.1</bias_mean>
				        <bias_stddev>0.001</bias_stddev>
				      </noise>
				    </z>
				  </linear_acceleration>
			</imu>
			<pose>0 0 0 0 0 0</pose>
			<update_rate>${rate_sensor}</update_rate>
    		<plugin name="gazebo_ros_imu_controller" filename="libgazebo_ros_imu_sensor.so"> 
    	  		<topicName>/imu</topicName>
    	  		<frameName>imu_link</frameName>
    	  		<alwaysOn>true</alwaysOn>
    	  		<bodyName>base_link</bodyName>
    	  		<gaussianNoise>0.5</gaussianNoise> 
    	  		<serviceName>imu/calibrate</serviceName>
    	  		<rpyOffset>0 0 0</rpyOffset> 
				<accelDrift>0.5 0.5 0.5</accelDrift>
				<accelGaussianNoise>0.35 0.35 0.35</accelGaussianNoise>
				<rateDrift>0.1 0.1 0.1</rateDrift>
				<rateGaussianNoise>0.05 0.05 0.05</rateGaussianNoise>
    		</plugin>
    	</sensor> 
  	</gazebo>
   
   
	<!-- Camera -->	
	<gazebo reference="camera_link">
		<material>Gazebo/Red</material>
		<sensor type="camera" name="camera_sensor">
		  <update_rate>${rate_sensor}</update_rate>
		  <camera>
			<horizontal_fov>1.047197551</horizontal_fov> <!--60 gradi-->
			<image>
			  <width>640</width>
			  <height>480</height>
			  <format>R8G8B8</format>
			</image>
			<clip>
			  <near>0.002</near>
			  <far>300</far>
			</clip>
			<noise>
			  <type>gaussian</type>
			  <mean>0.0</mean>
			  <stddev>0.0</stddev>
			</noise>
		  </camera>
		  <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
			<alwaysOn>true</alwaysOn>
			<updateRate>20.0</updateRate>
			<cameraName>wchair/camera_sensor</cameraName>
			<imageTopicName>image_raw</imageTopicName>
			<cameraInfoTopicName>camera_info</cameraInfoTopicName>
			<frameName>camera_link</frameName>
			<hackBaseline>0.0</hackBaseline>
			<distortionK1>0.0</distortionK1>
			<distortionK2>0.0</distortionK2>
			<distortionK3>0.0</distortionK3>
			<distortionT1>0.0</distortionT1>
			<distortionT2>0.0</distortionT2>
			<Cx>319.729675</Cx>
			<Cy>238.722791</Cy>
			<focalLength>554.668244</focalLength> <!--matematicamente 554.256258422-->
		  </plugin>
		</sensor>
  </gazebo>

<!-- ##################################################################### -->
	
	<!-- DIFFERENTIAL DRIVE CONTROLLER -->
	
	<gazebo>
		<plugin name="differential_drive_controller_caster" filename="libgazebo_ros_diff_drive.so">
			<legacyMode>false</legacyMode>
			<rosDebugLevel>Debug</rosDebugLevel>
			<publishWheelTF>true</publishWheelTF>
			<robotNamespace>/</robotNamespace>
			<publishTf>0</publishTf> 
			<broadcastTF>0</broadcastTF>
			<alwaysOn>true</alwaysOn>
			<publishWheelJointState>false</publishWheelJointState>
			<updateRate>${rate_sensor}</updateRate>
			<leftJoint>left_caster_joint</leftJoint>
			<rightJoint>right_caster_joint</rightJoint>
			<wheelSeparation>${base_y}</wheelSeparation>
			<wheelDiameter>0.2</wheelDiameter>
			<wheelTorque>30</wheelTorque>
			<wheelAcceleration>1.8</wheelAcceleration>
			<commandTopic>cmd_vel</commandTopic>
			<robotBaseFrame>base_link</robotBaseFrame>
			<odometryFrame>odom</odometryFrame> 
			<odometryTopic>odom</odometryTopic>
		</plugin>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<alwaysOn>true</alwaysOn>
			<legacyMode>false</legacyMode>
			<rosDebugLevel>na</rosDebugLevel>
			<robotNamespace>/</robotNamespace>
			<publishWheelTF>false</publishWheelTF>
			<publishWheelJointState>true</publishWheelJointState>
			<publishTf>1</publishTf> 	
			<updateRate>${rate_sensor}</updateRate>
			<leftJoint>left_wheel_joint</leftJoint>
			<rightJoint>right_wheel_joint</rightJoint>
			<wheelSeparation>${base_y}</wheelSeparation>
			<wheelDiameter>${2*wheel_radius}</wheelDiameter>
			<wheelTorque>30</wheelTorque>
			<wheelAcceleration>1.8</wheelAcceleration>
			<commandTopic>cmd_vel</commandTopic>
			<robotBaseFrame>base_link</robotBaseFrame>
			<odometryFrame>odom</odometryFrame> 
			<odometryTopic>odom</odometryTopic>
			<odometrySource>world</odometrySource>
		</plugin>
		<plugin name="differential_drive_controller_top" filename="libgazebo_ros_diff_drive.so">
			<legacyMode>false</legacyMode>
			<rosDebugLevel>Debug</rosDebugLevel>
			<publishWheelTF>true</publishWheelTF>
			<robotNamespace>/</robotNamespace>
			<publishTf>0</publishTf> 
			<broadcastTF>0</broadcastTF>
			<alwaysOn>true</alwaysOn>
			<publishWheelJointState>false</publishWheelJointState>
			<updateRate>${rate_sensor}</updateRate>
			<leftJoint>left_top_joint</leftJoint>
			<rightJoint>right_top_joint</rightJoint>
			<wheelSeparation>${base_y}</wheelSeparation>
			<wheelDiameter>0.05</wheelDiameter>
			<wheelTorque>30</wheelTorque>
			<wheelAcceleration>1.8</wheelAcceleration>
			<commandTopic>cmd_vel</commandTopic>
			<robotBaseFrame>base_link</robotBaseFrame>
			<odometryFrame>odom</odometryFrame> 
			<odometryTopic>odom</odometryTopic>
		</plugin>
	</gazebo>
</robot>

